### ISSUE TITLE
Problem while login 

### ISSUE THREAD

**Issue by viveklele** [therealsujitk/android-vtop-chennai#101]
While I tried to login with my vtop credentials it's showing error. It again and again asking to fill the captcha I don't know what to do
My device is Motorola g60
![Screenshot_20240103-222132](https://github.com/therealsujitk/android-vtop-chennai/assets/56582658/03244651-ac93-4672-bdfb-b34062e665dd)

**Comment by viveklele** [comment]
Yes I'm able to login

**Comment by viveklele** [comment]
> @viveklele are you able to sign in to VTOP using the same credentials?

Yes I'm able to login

**Comment by therealsujitk** [comment]
@viveklele by any chance does your username or password contain a single quote (`'`)?

**Comment by viveklele** [comment]
> > @viveklele by any chance does your username or password contain a single quote (`'`)?
> 
> If so, this should be fixed in the next release (> **v4.3.2**).

Yes

**Comment by viveklele** [comment]
> > @viveklele by any chance does your username or password contain a single quote (`'`)?
> 
> If so, this should be fixed in the next release (> **v4.3.2**).

Yes it contains a single quote
