### ISSUE TITLE
Can you develop a similar app for ios/ipados versions?

### ISSUE THREAD

**Issue by GokulGirish0202** [therealsujitk/android-vtop-chennai#102]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. eg. I have an issue when [...]

**Describe the solution you'd like**
A detailed description of your proposed solution. Include:

- How the feature would work/behave
- Any potential drawbacks
- Maybe a screenshot, design, or example code

**Comment by therealsujitk** [comment]
I had initially planned to create an iOS variant as well, but I never found the time to pursue it 😕. Now, with my current workload and other projects, I'm afraid I won't be able to allocate time for it. Hopefully, someone else will pick it up in the future.
