### ISSUE TITLE
Use weighted average to calculate overall attendance

### ISSUE THREAD

**Issue by lemonredwood** [therealsujitk/android-vtop-chennai#104]
## Bug Report

**Current Behavior**
Currently, the overall attendance is computed by averaging the attendance of all courses, regardless of the total number of classes. Instead of a simple average, it is recommended to use the weighted average of course attendance to accurately calculate the overall average for a student.

**Expected Behavior**
The overall attendance calculation should account for both the total number of classes conducted across all courses and the total number of classes attended by the student. This approach would yield a more accurate total attendance calculation, contrasting with the current method of averaging the percentages of all courses, which leads to inaccuracies in overall attendance.

**Additional Context**
Upon independently calculating my actual attendance by dividing the total classes attended by the total number of classes held, I discovered that the displayed overall attendance was inaccurate. It merely reflected the average of all course attendance percentages. I am willing to contribute by providing the accurate attendance information. You can reach out to me on LinkedIn at [linkedin.com/in/rohith-anand-026578262](https://www.linkedin.com/in/rohith-anand-026578262).

**Comment by lemonredwood** [comment]
Should I start working on this?

**Comment by therealsujitk** [comment]
> Should I start working on this?

Sure! Create a PR and I'll review it when I'm free. Let me know if you need any help, thanks!

**Comment by ezhil56x** [comment]
@lemonredwood
Are you still working on this, or can I take up?

**Comment by lemonredwood** [comment]
I was a bit busy and planned on working on it in a week. If you want we both can work on it together.Let me know.

**Comment by ezhil56x** [comment]
@lemonredwood 

If so can I take up this? This is a small issue one person can fix it

**Comment by lemonredwood** [comment]
I'll do it then? It would be my first ever contribution. I hope you understand.

**Comment by therealsujitk** [comment]
I'll assign this to @lemonredwood since he asked for it first.

**Comment by ezhil56x** [comment]
@lemonredwood 
Are you still on this?

**Comment by therealsujitk** [comment]
@lemonredwood any update on this?

**Comment by therealsujitk** [comment]
Alright, I'll reassign this issue since @lemonredwood doesn't seem to be available.
