### ISSUE TITLE
Data Syncing Fails with Error 201 - No value for semesters.

### ISSUE THREAD

**Issue by krishnasharmak05** [therealsujitk/android-vtop-chennai#105]
## Bug Report

**Current Behavior**
When syncing data, after filling the captcha, error 201 appears, which results in the captcha reappearing. This behavior keeps looping.

**Steps to Reproduce**

1. Go to 'Profile'
2. Click on 'Sync Data'
3. Fill Captcha
4. "Error 201. No value for semesters" appears.
5. Captcha Reappears.

**Expected Behavior**
Expected to see a successful login and sync of data.

**Screen Recording Video**
[Screen Recording Video](https://github.com/therealsujitk/android-vtop-chennai/assets/146259706/485b8824-123f-4235-8fe8-95ef720347a7)

**Environment**

- Android version: 13 (MIUI), 14 (OxygenOS)

**Comment by jessej-samuel** [comment]
Facing the same issue

**Comment by OneRandom1509** [comment]
Same issue here too!

**Comment by SuvanshRao** [comment]
same issue, couldnt sync for 2 days

**Comment by therealsujitk** [comment]
It's an issue with the user agent, it's outdated, I'll release an update by tonight.

**Comment by therealsujitk** [comment]
Fixed in **v4.3.4**.

**Comment by therealsujitk** [comment]
Issue occurred again in #109. (Commenting this for reference)
