### ISSUE TITLE
Not able to sync 

### ISSUE THREAD

**Issue by Max-Eee** [therealsujitk/android-vtop-chennai#106]
## Bug Report

**Current Behavior**
when I try to sync data after entering the captcha I'm not able to select the semester instead a popup says "no value for semester"

**Steps to Reproduce**

1. Go to 'Profile'
2. Click on 'Sync Data'
3. Fill in the captcha
4. See error (no value for semester)

**Expected Behavior**
the user should be able to select the semester and sync the data

**Screenshots**
![Screenshot_20240315-070136.png](https://github.com/therealsujitk/android-vtop-chennai/assets/76102874/655dcb39-bd1f-48e2-a6b3-98e11d26b4cd)

**Environment**

- Android version: 
- Device make & model:

**Comment by adithyasunil04** [comment]
+1

**Comment by therealsujitk** [comment]
Closing as duplicate of #105.
