### ISSUE TITLE
Overall Credits Earned is not updating. 

### ISSUE THREAD

**Issue by vinayak-didwania** [therealsujitk/android-vtop-chennai#118]
## Bug Report

**Current Behavior**
My current overall Credits earned in the VIT Student App is showing 102.5 

**Expected Behavior**
But my correct current overall Credits earned as shown on VTOP is 111.5

**Environment**
- Android version: Android 14
- Device make & model: Samsung Galaxy A34 5G

**Comment by therealsujitk** [comment]
I'll assume this was a mistake.
