### ISSUE TITLE
Reappearance of Error 201- No value for Semesters

### ISSUE THREAD

**Issue by AishikTokdar** [therealsujitk/android-vtop-chennai#119]
It is Error 201, it has again started appearing.

See #109 for reference

**Comment by therealsujitk** [comment]
Ugh, I'll have to take a look. VIT is being extremely immature about this by pulling these cheap tricks. If they want people to use their app, they should just make it better. 🤦‍♂️

**Comment by therealsujitk** [comment]
This issue is unrelated to #109, they just updated the endpoint they use to get semesters.
