### ISSUE TITLE
Fresher not able to log into app due to "Select Semester" error?

### ISSUE THREAD

**Issue by Derpitron** [therealsujitk/android-vtop-chennai#124]
I'm a fresher, to join VIT Chennai in 2024.

I tried to log into your VIT Student app with my VTOP credentials. 

But it shows a modal dialogue, asking me to select Semester. But the list is blank, there is no selection.

I assume this is because I've not formally enrolled yet so the VTOP backend doesn't know what semester to put me in. 

In this case what should I do? Should I wait for a while?

 Thank you for your work!

**Comment by therealsujitk** [comment]
Yes, you'll have to wait until you get your timetable, the app won't be of much use to you until then anyway.
