### ISSUE TITLE
Incorrect attendance excess displayed for some courses

### ISSUE THREAD

**Issue by sheshank1212** [therealsujitk/android-vtop-chennai#125]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**

1. Go to 'Application'
2. Click on 'Class'
3.See error

**Expected Behavior**
It has be calculated upto 75

**Environment**

- Android version: <Android 14 >
- Device make & model: < Realme 9 pro plus >
- 
**Screenshots**
![Screenshot_2024-07-25-08-38-39-10_6573c7e73bb09b157d08de748cac469a](https://github.com/user-attachments/assets/69a50b04-ae61-4486-a167-9ed32bb2d8ab)

**Comment by therealsujitk** [comment]
@sheshank1212 can you share the total and attended values as well.

**Comment by therealsujitk** [comment]
Resolved in 99f98232f459164cc2eb1fb87ffcdf1c8f2a808b, will be released in the next **v4.3.7**.
