### ISSUE TITLE
Unable to download the app

### ISSUE THREAD

**Issue by Kamalesh-1** [therealsujitk/android-vtop-chennai#128]
Not able to download the app after the software update.

**Comment by therealsujitk** [comment]
- If the download button on [the download page](https://vtopchennai.therealsuji.tk/) doesn't work, you can try right clicking (or long clicking) the button to open it in a new tab.
- Alternatively go to [the releases page](https://github.com/therealsujitk/android-vtop-chennai/releases) here on GitHub and click the **.apk** file under assets to download it.
