### ISSUE TITLE
Semester is missing from this list. 

### ISSUE THREAD

**Issue by virenhooda27** [therealsujitk/android-vtop-chennai#133]
![Screenshot_2024-12-21-09-02-26-829_tk therealsuji vtopchennai](https://github.com/user-attachments/assets/8ca918fb-707e-4aa7-94ec-1d4945f8ec23)
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Environment**

- Android version: 
- Device make & model: 

**Possible Solution**

**Additional Context**

**Comment by virenhooda27** [comment]
Fallsem 2024-25 is missing

**Comment by naman-0804** [comment]
Yes , it's not visible

**Comment by naman-0804** [comment]
It is from vtop side , it's also missing from vtop timetable u can check > Fallsem 2024-25 is missing

**Comment by therealsujitk** [comment]
This app picks up semesters from the timetable page on VTOP. So if it isn't present there, it won't be in the app.
