### ISSUE TITLE
Option to pick color for the interface. 

### ISSUE THREAD

**Issue by Abhir1902** [therealsujitk/android-vtop-chennai#20]
## Feature Request

Add an option to customise the user interface colors.

**Comment by therealsujitk** [comment]
@Abhir1902 the current theme implements Material You which is already customizable but only for devices running android 12 and above. [This issue](https://github.com/therealsujitk/android-vtop-chennai/issues/18#issue-1155628107) shows a video of a device running android 12 with a blue theme.
