### ISSUE TITLE
App crashes when trying to view receipts

### ISSUE THREAD

**Issue by praneeth-bojanala5** [therealsujitk/android-vtop-chennai#21]
## Bug Report

App crashes when I click on Receipts

**Comment by therealsujitk** [comment]
@praneeth-bojanala5 can you provide a screenshot of your receipts page from VTOP? It looks like this bug is user specific.

**Comment by therealsujitk** [comment]
@praneeth-bojanala5 please follow the template provided while giving bug reports, it would be great if you could provide your device information (Android version, device make). This seems to be a bug only affecting you, so I will need a screenshot of your receipts page from VTOP.

![image](https://user-images.githubusercontent.com/60378235/159514044-6e3e98fc-2b38-4f12-a1e4-d7b90b2b2a01.png)

If you're not comfortable sharing this page on GitHub, you can email it to me.

**Comment by praneeth-bojanala5** [comment]
Android version: 11
Device: Samsung galaxy a-50

**Comment by praneeth-bojanala5** [comment]
> @praneeth-bojanala5 thanks for the email, it looks like [this line](https://github.com/therealsujitk/android-vtop-chennai/blob/master/app/src/main/java/tk/therealsuji/vtopchennai/services/VTOPService.java#L1932) is what's causing the crash. Since some of the amount values in your receipts is 0, `receipt.amount = parseInt(0) || null` sets the amount to `null` instead of `0`. This causes a `NullPointerException`. This issue will be resolved in the next release.

👍
