### ISSUE TITLE
Opening courses crashes the app

### ISSUE THREAD

**Issue by VARUNKUMAR15** [therealsujitk/android-vtop-chennai#27]
## Bug Report

In the course section when I access some courses the app crashes.

**Comment by therealsujitk** [comment]
@VARUNKUMAR15 can you provide more information about this issue? A screenshot of your courses page from VTOP would be great.

**Comment by VARUNKUMAR15** [comment]
This is the issue sometimes for some courses tooo

**Comment by therealsujitk** [comment]
@VARUNKUMAR15 can you check if you still have this issue in **v4.0.1**.

**Comment by therealsujitk** [comment]
Closing as a duplicate of #18.
