### ISSUE TITLE
App doesn't work for summer semester

### ISSUE THREAD

**Issue by pratham-jaiswal** [therealsujitk/android-vtop-chennai#29]
## Bug Report

**Current Behavior**
Not displaying anything for Summer Semester.

**Error Thrown**
"Error 501. No value for sunday"

**Screenshots**
![Screenshot_20220512-132731_VIT Student](https://user-images.githubusercontent.com/72384535/168021220-271c9b8c-7679-4771-8d2e-8620d0008e26.jpg)

**Comment by therealsujitk** [comment]
@pratham-jaiswal can you upload your summer semester timetable here.
