### ISSUE TITLE
Web Scrapping the data

### ISSUE THREAD

**Issue by Pranshu1902** [therealsujitk/android-vtop-chennai#43]
Could you please explain how exactly you scraped all the data and went beyond the login page? Like did you use any extension or made your own scraper?

**Comment by therealsujitk** [comment]
No extension, I used JavaScript to scrape all the data. It is a very time-consuming process but I did have a lot of time in my first year. The [`VTOPService.java`](https://github.com/therealsujitk/android-vtop-chennai/blob/master/app/src/main/java/tk/therealsuji/vtopchennai/services/VTOPService.java) file contains all the JS code I've used to extract data from the portal.
