### ISSUE TITLE
App crashes when tapping on a subject in timetable

### ISSUE THREAD

**Issue by agileAlligator** [therealsujitk/android-vtop-chennai#47]
## Bug Report

When you tap on subject to open up a pane that tells you where the class is, the app immediately crashes

**Steps to Reproduce**

1. Go to home page
2. Click on any subject 
3. See app crash

**Expected Behavior**
App shows me location of class

**Environment**

- Android version: 
- Device make & model:

**Comment by therealsujitk** [comment]
Closing this issue as a duplicate of #45.
