### ISSUE TITLE
App closes when I click on "Performance"

### ISSUE THREAD

**Issue by Sha-Dow-Mon-Arch** [therealsujitk/android-vtop-chennai#53]
## Bug Report

**Current Behavior**
In the recent version of this app, when i click on the "Performance" icon, the app closes

**Expected Behavior**
The app should ideally show my Performance page instead of closing the app

**Environment**

- Android version: Android 12
- Device make & model: Realme 9 Pro+

**Comment by therealsujitk** [comment]
@Sha-Dow-Mon-Arch can you provide a screenshot of your marks page from VTOP and share it here, if you're more comfortable with sharing it with me personally you can email it to me at social@therealsuji.tk.

**Comment by therealsujitk** [comment]
Fixed in 22a4a22c009d9aa019bc3d7518ea7be897ad13e2. Changes will be reflected from **v4.2.1**.

**Comment by Sha-Dow-Mon-Arch** [comment]
Thanks a lot!!
