### ISSUE TITLE
Error 103: value of null type

### ISSUE THREAD

**Issue by ProficientPug** [therealsujitk/android-vtop-chennai#56]
## Bug Report

**Current Behavior**
Data doesn't sync with vtop

**Steps to Reproduce**

1. Go to settings
2. Click on sync data
3. See error

**Expected Behavior**

Data sync should have been successful
**Screenshots**
I
![Screenshot_20220907-143211](https://user-images.githubusercontent.com/68496832/188837699-e9eeafd9-4b82-4aa4-9bf1-0424123113d8.png)

**Environment**

- Android version:  Android 12
- Device make & model: Xiaomi mi 11x

**Possible Solution**

**Additional Context**

**Comment by therealsujitk** [comment]
It looks like you weren't connected to the internet when you attempted to sync data. Try syncing again when you are connected.
