### ISSUE TITLE
Offset issue while syncing data for unapproved students

### ISSUE THREAD

**Issue by therealsujitk** [therealsujitk/android-vtop-chennai#57]
When students haven't completed their fee payment, data gets offset and is stored in the wrong tables.

**Note:** More information is required to pinpoint where exactly this issue occurs.

_Originally posted by @therealsujitk in https://github.com/therealsujitk/android-vtop-chennai/issues/44#issuecomment-1206351695_

**Comment by thebluedev** [comment]
Just checked after update, issue still occurs.

**Comment by therealsujitk** [comment]
Are you in A block by any chance?

**Comment by thebluedev** [comment]
Nope, I'm a day scholar

**Comment by therealsujitk** [comment]
@thebluedev can you still reproduce this issue?

**Comment by thebluedev** [comment]
Nope, it went away as soon as the last day for paying for the send passed.

**Comment by therealsujitk** [comment]
I think it should be fixed now, will be shipped with the next release (>**v4.3.2**). I'll be closing this for now but it'll be great if someone can confirm if this is fixed or not in future, I'll keep this issue pinned.
