### ISSUE TITLE
a place to see mess timings along with other shops in vit chennai

### ISSUE THREAD

**Issue by KATT07** [therealsujitk/android-vtop-chennai#58]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. eg. I have an issue when [...]

**Describe the solution you'd like**
A detailed description of your proposed solution. Include:

- How the feature would work/behave
- Any potential drawbacks
- Maybe a screenshot, design, or example code

**Comment by therealsujitk** [comment]
@KATT07 this feature was present in an older version however it's been removed as it wasn't very helpful. There aren't a lot of shops in campus (Chennai) so it doesn't take long for freshers to get familiar with the area. I believe the android club made a freshers app released on play store specifically for this.
