### ISSUE TITLE
Link the app to Google Calendar 

### ISSUE THREAD

**Issue by SuryaThangaraju** [therealsujitk/android-vtop-chennai#59]
Could please enable this feature wherein the VIT Student app automatically schedules time slots on the Google Calendar with the Room no. As I spend an hour on this every week, it would be really helpful for everybody if this feature gets included in.

**Comment by therealsujitk** [comment]
@SuryaThangaraju is there a good reason for this feature? The app already notifies students on classes and gives the venue in the app.

**Comment by therealsujitk** [comment]
I'll be closing this as there has been no response from you.
