### ISSUE TITLE
App being detected as a trojan virus on installation (False Positive)

### ISSUE THREAD

**Issue by skp6850** [therealsujitk/android-vtop-chennai#64]
Asking For Permissions
android.permission.READ_EXTERNAL_STORAGE 
android.permission.WRITE_EXTERNAL_STORAGE

Avast-Mobile

**Android:Evo-gen [Trj]**

[Remote Access Functionality (1)](https://vtbehaviour.commondatastorage.googleapis.com/21d62044365a316746ef7e26d619eb998807c2eb56d622baa65a23e850cb7cc9_Zenbox%20android.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1669180370&Signature=cog1%2BNUx2eJS2CGAwo9l24VJvm73usVlWk%2BgxC1aW6zL%2BhLWy8CpsyTFPRMu5qlECx5G7H5SZMNC%0AvbW3xE6nkLLUe0wHxpVssM23is3yLvjzLgqHyNk41ScqvHj50Vu4cdjtus4Xw1Wbhsxwia%2BU%2Bjhs%0Aw82VXmHCkjM3iN%2Bndcbxh0SGJZKpRoPdO%2Bw%2FwMZgV%2BPTdr8X%2BDK99umCUvba2bqTonFDC5ERNpIZ%0A7xcAUprRuAP3m3Mepat%2BJggM8S%2FNKYMrag%2BN3bLp8O3hq0sCqTbbz47N1YSW%2Bp4pl5k17ELuGVTW%0AxMse14Vw%2B9WKpYBcP4o57fE82IjUdPUs5RhdBQ%3D%3D&response-content-type=text%2Fhtml;#remote-access-functionality)
1.0
Uses DownloadManager to fetch additional components

**Comment by therealsujitk** [comment]
@skp6850 what is your question? If you're asking what these permissions are for, it's for allowing access to storage so you can download files from moodle, spotlight and upload assignments to moodle. It's certainly not a trojan so be at ease :joy:

**Comment by skp6850** [comment]
It's showing as Trojan virus on installation .

**Comment by therealsujitk** [comment]
Looks like [other people](https://forum.avast.com/index.php?topic=304817.0) have faced this issue as well. For now I've reported it to Avast as a false positive and am waiting for them to get back to me.

![image](https://user-images.githubusercontent.com/60378235/203497265-2eaa9d25-e791-42ad-b2b5-8b6c14cccd78.png)

**Comment by therealsujitk** [comment]
@skp6850 are you still facing this issue? I think it should be rectified now.

**Comment by therealsujitk** [comment]
Got a response from Avast too.

![image](https://user-images.githubusercontent.com/60378235/204073011-9b0add2b-0e39-4ec1-8552-a0ba43dc8b16.png)
