### ISSUE TITLE
Timetable not showing after availing weekend intra course 

### ISSUE THREAD

**Issue by Dharsh1024** [therealsujitk/android-vtop-chennai#69]
## Bug Report

**Current Behavior**
Timetable not showing after availing weekend intra course .

**Steps to Reproduce**

1. Go to  vit student app main page
2. See error
![Screenshot_2022-12-20-08-41-20-82_6573c7e73bb09b157d08de748cac469a](https://user-images.githubusercontent.com/117929743/208572739-ed4af24e-f139-4e85-bd5d-df84d531f0f9.jpg)

- Android version:  Android 12 
- Device make & model:  OnePlus Nord 1 

**Possible Solution**

**Additional Context**

**Comment by prasadnaik-null** [comment]
i did have a similar problem while taking a backlog course in normal sem... the timetable was shown after i completed the payment tho

**Comment by therealsujitk** [comment]
Yes, @Dharsh1024 & @prasadnaik-null, this is a known issue opened in #57 & #68. There is a scraping issue due to the slight difference in the layout when some courses are not approved (i.e. payment not completed).

I'll close this issue as a duplicate, it will be patched in the next release.
