### ISSUE TITLE
To toggle do not disturb on in an ongoing class

### ISSUE THREAD

**Issue by ashishsaranshakya** [therealsujitk/android-vtop-chennai#71]
## To toggle do not disturb on in an ongoing class

**Is your feature request related to a problem? Please describe.**
we have to manually turn on do not disturb on and off whenever in class

**Describe the solution you'd like**
- The feature would include the option to put your phone on either vibrate or silent
- Screetshot
<img src="https://user-images.githubusercontent.com/74979286/212269034-ff5ce594-56b8-44cd-be7e-ca583f655bd2.jpg" width="300" height="600">

**Comment by ashishsaranshakya** [comment]
assign me

**Comment by therealsujitk** [comment]
What exactly is this feature request for? Can you explain a bit more?

**Comment by ashishsaranshakya** [comment]
The request includes a feature which will turn on the do not disturb mode
during class and turn it off after class so that people's phones do not
ring between classes. and if they have turned it to vibrate mode then it
will vibrate instead of ringing.

**Comment by ashishsaranshakya** [comment]
what should I do now with this feature
