### ISSUE TITLE
Display receipts sorted by date

### ISSUE THREAD

**Issue by issaspaceboy** [therealsujitk/android-vtop-chennai#72]
If you would sort the receipts by date in the app it would be more convenient for us to remember what the receipts are about. Sorting the receipts by number is pretty much useless (for me at least).

**Comment by ramumaha** [comment]
hey,,,
I am interest to work in this issue..Can you provide me some more details and assign me the task
thanks

**Comment by therealsujitk** [comment]
Hi @ramumaha, thanks for your interest in this project!

The [`attachReceipts()`](https://github.com/therealsujitk/android-vtop-chennai/blob/master/app/src/main/java/tk/therealsuji/vtopchennai/fragments/RecyclerViewFragment.java#L45) function is responsible for displaying the receipts to the user, the list of receipts is passed through an adapter class on [this line](https://github.com/therealsujitk/android-vtop-chennai/blob/master/app/src/main/java/tk/therealsuji/vtopchennai/fragments/RecyclerViewFragment.java#L64), meaning the list has to be sorted before it is passed. You'll have to sort this object by it's `date` property. Let me know if you'd like any more help.

**Comment by ramumaha** [comment]
right right..
So..the receipts must be sorted by date before it gets sent to the adapter class.. correct?
Can you assign the issue to me..So that I shall start working on it
Thanks

**Comment by therealsujitk** [comment]
@ramumaha make sure to do it in descending order, latest receipt on the top.

**Comment by ezhil56x** [comment]
Hi @therealsujitk I'm interested to work on this. Is this already completed or not yet started ?

**Comment by therealsujitk** [comment]
@ramumaha any updates regarding this issue?

**Comment by ramumaha** [comment]
Hii..
I am sorry..
I was working on it when I was put into a different emergency work..
Ig you can count me out

**Comment by ezhil56x** [comment]
@therealsujitk I have completed this and created a new pull request
