### ISSUE TITLE
Server error after VTOP update

### ISSUE THREAD

**Issue by therealsujitk** [therealsujitk/android-vtop-chennai#74]
## Bug Report

VIT Student throws a server error while trying to sync data after the latest VTOP update.

**Comment by Pranshu1902** [comment]
@therealsujitk  I can work on this issue in case you need any help with a sub-task.

**Comment by therealsujitk** [comment]
> @therealsujitk I can work on this issue in case you need any help with a sub-task.

I think only the signing in code is to be update for which I've already written up something rough, I just need to test it. I currently have exams going on which is why I'm not able to do this faster.

**Comment by Pranshu1902** [comment]
@therealsujitk oh that's great. do let me know in case you need any help

**Comment by namansrivastava1608** [comment]
Still it is saying server error on the app

**Comment by namansrivastava1608** [comment]
It is still showing the same server error on app and on the login page it keeps on logging in forever

**Comment by therealsujitk** [comment]
> It is still showing the same server error on app and on the login page it keeps on logging in forever

Yeah, this release hasn't been pushed out yet. I'll do it after CAT when I add a few more fixes.

**Comment by CrypticVader** [comment]
I still cannot login after updating the app, tried clearing the app's data.

**Comment by therealsujitk** [comment]
@CrypticVader are you sure you're on **v4.2.2**? You can check this in settings.

**Comment by CrypticVader** [comment]
Yes[]()

**Comment by CrypticVader** [comment]
![Screenshot_20230201-224222-794.png](https://user-images.githubusercontent.com/61494838/216113835-d697526f-b3e6-418c-8109-26e23695c602.png)

**Comment by CrypticVader** [comment]
![Screenshot_20230201-224222-794.png](https://user-images.githubusercontent.com/61494838/216113835-d697526f-b3e6-418c-8109-26e23695c602.png)

**Comment by CrypticVader** [comment]
![Screenshot_20230201-224820-748.png](https://user-images.githubusercontent.com/61494838/216115625-dee5fa1c-e4c6-4878-8957-04a068f35f1a.png)

**Comment by CrypticVader** [comment]
It's working now, It seems like after getting multiple invalid passwords on the previous version after the vtop update, i had reached maximum retries and was required to update my password (which I got to know after opening vtop)
