### ISSUE TITLE
Unable to Sync Data due to New VTOP update 

### ISSUE THREAD

**Issue by ShyamSundhar1411** [therealsujitk/android-vtop-chennai#77]
## Bug Report
Since the VTOP is updated, the api endpoints are updated as well, due to which there is sync error. Kindly look on to this issue
**Current Behavior**
A clear and concise description of the behavior.
Due to change in api end points it's producing a 101 null error message.
**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Environment**

- Android version: 
- Device make & model: 

**Possible Solution**

**Additional Context**

**Comment by therealsujitk** [comment]
Opened in #74.
