### ISSUE TITLE
Error 103

### ISSUE THREAD

**Issue by Kdxii** [therealsujitk/android-vtop-chennai#78]
![Screenshot_20230130-083222__01](https://user-images.githubusercontent.com/123917633/215380224-3be969bc-ce8b-4ee7-b036-3d568bedb694.jpg)
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Environment**

- Android version: 
- Device make & model: 

**Possible Solution**

**Additional Context**

**Comment by therealsujitk** [comment]
Opened in #74.
