### ISSUE TITLE
Error 101

### ISSUE THREAD

**Issue by praneeth55** [therealsujitk/android-vtop-chennai#81]
I can't login. It shows error 101 and error 103

**Comment by therealsujitk** [comment]
@praneeth55 have you updated to the latest verison **v4.2.2**?

**Comment by praneeth55** [comment]
> @praneeth55 have you updated to the latest verison **v4.2.2**?

Yes

**Comment by praneeth55** [comment]
> @praneeth55 have you updated to the latest verison **v4.2.2**?

Don't worry it's working now. I deleted and installed again

**Comment by raja1809** [comment]
It's showing error 101 for me for a long time...

**Comment by therealsujitk** [comment]
> It's showing error 101 for me for a long time...

@raja1809 are you able to sign in on VTOP?

**Comment by raja1809** [comment]
Yess i can... Can't login in app only bro... 🥲
