### ISSUE TITLE
Add feature to show class average and deviation

### ISSUE THREAD

**Issue by yashrathi-git** [therealsujitk/android-vtop-chennai#85]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Generally teachers tell the average but won't tell the deviation. So would be helpful to have this feature.

**Describe the solution you'd like**
A detailed description of your proposed solution. Include:
Store and collect the marks of each student, and show average and deviation in the performance tab.

**Drawback**

* The only drawback or constraint would be that it would have to collect some data about students' marks.

**Comment by therealsujitk** [comment]
The first problem with this is not everyone will be comfortable with my collecting their marks (even if it's anonymous).

Even if marks were collected anonymously to calculate the deviation and average, the other problem is that not all students use this application (iOS users for example 😛) which may result in incorrect information being displayed. Even if we give people the option to **opt-in**, we'll face the same issue.

All this aside there's the issue of servers, how to collect data when people sync (not all of them do it very often), and so many more headaches 😩.

So, for now I'll be closing this as unplanned 🙂.
