### ISSUE TITLE
Error 105, Value null .. while syncing in the app

### ISSUE THREAD

**Issue by un-identified** [therealsujitk/android-vtop-chennai#93]
It is continuosly giving this error while syncing
![Screenshot_2023-08-11-16-48-58-421_tk therealsuji vtopchennai](https://github.com/therealsujitk/android-vtop-chennai/assets/110972759/b53c2c55-cfdb-41c6-ac35-8042b3521a0f)

**Comment by SheikahProgrammer** [comment]
Same.

**Comment by Max-Eee** [comment]
same here

**Comment by therealsujitk** [comment]
Will try pushing the next release by EOD.

**Comment by TheOddOnEE** [comment]
Any update regarding the issue?
