### ISSUE TITLE
Data not syncing 

### ISSUE THREAD

**Issue by rohan-charapale** [therealsujitk/android-vtop-chennai#94]
![Screenshot_20230813_023849_VIT Student](https://github.com/therealsujitk/android-vtop-chennai/assets/94275246/09877f32-6a66-4142-a11b-0d4c2f756b88)
 After clicking on sync data it shows error 105 value null

Andriod version : 13
Brand samsung

**Comment by therealsujitk** [comment]
Opened in #93
