### ISSUE TITLE
Storage permission denied

### ISSUE THREAD

**Issue by sppidy** [therealsujitk/android-vtop-chennai#97]
## Bug Report

**Current Behavior**
Please include permissions for storage assignments and others files cant be downloaded 

**Steps to Reproduce**

1. Go to assignments 
2. Login and click on a assignment which has some files
3. Try downloading it 

**Expected Behavior**
The file should be downloaded to the storage

**Screenshots**
![Screenshot_20230907_141831_VIT Student.jpg](https://github.com/therealsujitk/android-vtop-chennai/assets/68327188/51619d72-5ac2-4ef4-a643-17d09e1417b3)

**Environment**

- Android version:  Android 13
- Device make & model: Samsung a54 5g 

**Possible Solution**
Add storage permissions

**Comment by therealsujitk** [comment]
@sppidy as a workaround, you can go to settings and allow File & media access.

**Comment by sppidy** [comment]
Actually i have tried it before but as you see here the app doesnt even
request storage permissions

**Comment by therealsujitk** [comment]
@sppidy I might have forgotten to open the permission prompt. Can you try downloading a file from Spotlight? It should ask for permission.

**Comment by sppidy** [comment]
https://github.com/therealsujitk/android-vtop-chennai/assets/68327188/5568a3b7-1c99-4b44-a7e9-4ba0f22756e6

**Comment by therealsujitk** [comment]
Fixed in **v4.3.1**.
