### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by SafeeqAhamed** [therealsujitk/android-vtop-chennai#99]
#36 .
After entering my ID and password,and also captcha verification it is not logging in ,instead it is displaying unknown error

Please rectify it🙏

**Comment by therealsujitk** [comment]
@SafeeqAhamed are you able to login to VTOP in your browser?

**Comment by SafeeqAhamed** [comment]
> @SafeeqAhamed are you able to login to VTOP in your browser?

Yess!..But unable to login in your app

**Comment by thebluedev** [comment]
@SafeeqAhamed Have you changed your password recently? if so log out inside the app then log in again, That should fix it.

The unknown error is probably caused by the app using the old password to try and login

**Comment by SafeeqAhamed** [comment]
No I haven't changed password

**Comment by therealsujitk** [comment]
@SafeeqAhamed does logging in and logging out fix the issue?

**Comment by SafeeqAhamed** [comment]
Im not even able to login....

**Comment by therealsujitk** [comment]
> Have you changed your password recently? if so log out inside the app then log in again, That should fix it. The unknown error is probably caused by the app using the old password to try and login

@thebluedev The application should have handled this case by logging the user out, but it seems like at some point I accidentally removed this case and didn't put it back.

@SafeeqAhamed as for your issue I'm not sure what's wrong as it seems like you're the only one facing it, what version of the app are you on? Have you tried updating to the latest version?

**Comment by therealsujitk** [comment]
Since I haven't heard from you I'll assume the issue has been resolved, so I'll be closing it. If you're still facing this, feel free to reopen it.
